# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Deploy to GCP Cloud Run

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./redirects-health-monitor
    
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Get current versions
      run: |
        git version
        docker version
        docker-compose version
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test and Build with Gradle
      run: ./gradlew test && ./gradlew build

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Test Results
        # Required recipients' addresses:
        to: karthik.narahari1@gmail.com
        # Required sender full name (address can be skipped):
        from: Karthik Narahari # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: ./build/reports/tests/test/index.html
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low

    - name: Build & push Docker image to GCP
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: search-playground-8065/gcf/europe-west3/7e79088e-98fc-4c3e-b3c5-7d702989e78f/redirects-health-monitor
        tags: latest
        registry: eu.gcr.io
        dockerfile: ./redirects-health-monitor/Dockerfile
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: ${{ secrets.GCP_SA_NAME }}
        project_id: $ {{ secrets.GCP_PROJECT_ID }}
        image: eu.gcr.io/search-playground-8065/gcf/europe-west3/7e79088e-98fc-4c3e-b3c5-7d702989e78f/redirects-health-monitor:latest
        region: europe-west3
        credentials: ${{ secrets.GCP_SA_KEY }}
